### ISSUE TITLE
Don't ignore *.Rproj files

### ISSUE THREAD

**Issue by katrinleinweber** [carpentries-incubator/git-Rstudio-course#3]
The most widely-used [`.gitignore` template](https://github.com/toptal/gitignore/blob/master/templates/R.gitignore) doesn't, because it is just as much _project_-, as it is [user/computer](https://github.com/carpentries-incubator/git-Rstudio-course/blob/ed66629c0124b7788b6eb59ec8086a47fb3e6c21/_episodes/02-ignore.md#gitignore)- specific. Therefore, people who want to contribute to one's project should be able to clone the `.Rproj` file as well.

**Comment by orchid00** [comment]
Hi @katrinleinweber, sorry I missed this. I'm not sure I understand what the suggestion is here. Could you please rephrase. Is it that there's different scenarios for when you would add the .Rproj to the ignore list? I generally ignore it. Could you add some documentation please?

**Comment by katrinleinweber** [comment]
Sure, see https://community.rstudio.com/t/should-rproj-files-be-added-to-gitignore/1269/.

Also, people who clone the project probably want to double-click that file to open the project _and_ have the IDE switch the working directory to the project path, just as the maintainer can do.

**Comment by orchid00** [comment]
Thanks @katrinleinweber I'll review this again, I will leave this open if you don't mind.

**Comment by katrinleinweber** [comment]
I don't mind at all. No hurry here :-)

**Comment by AndreaSanchezTapia** [comment]
Hi! I agree and would like to add an important reason for keeping the .Rproj files in this specific lesson: the git pane won't appear unless you are inside an RStudio project. The .Rproj file will have to be re-created locally if it's not there when executing pull.

**Comment by orchid00** [comment]
I need to apologize @katrinleinweber for taking forever. I had left this buried down a big pile :(
Thanks for reminding me @AndreaSanchezTapia  :) 
Finally fixed this with this commit https://github.com/carpentries-incubator/git-Rstudio-course/commit/031131065058bbf504e5b44ac320f0c734a92bde
